### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by limelect** [fpiette/Direct2DDemo#1]
D10.2.3
with             FBitmapToPaint := CreateDirect2DBitmap(
                            AcceleratedPaintPanel1.D2DCanvas.RenderTarget,
                            GPBitmap);
   EAccessViolation: Access violation at address 005F8D12 in module 'Direct2DDemo.exe'. Read of address 00000060

Picture Delphi25 ICS.jpg is there and find it.

P.s i did not use TAcceleratedPaintPanel as a component but

          AcceleratedPaintPanel1:= TAcceleratedPaintPanel.Create(Self); <<<<<tried either one
 AcceleratedPaintPanel1:= TAcceleratedPaintPanel.Create(TopPanel);<<<<<tried either one
also Direct2DDemoMainForm<<<<<<<<<<<<<<
 
   with AcceleratedPaintPanel1 do
    begin
 //    object AcceleratedPaintPanel1: TAcceleratedPaintPanel
      Left := 1;
      Top := 1;
      Width := 408;
      Height := 339;
      Align := alClient;
      ParentBackground := False;
      TabOrder := 0;
      OnClick := AcceleratedPaintPanel1Click;
      OnPaint := AcceleratedPaintBox1Paint;

    end;
where on private i have        AcceleratedPaintPanel1: TAcceleratedPaintPanel;
too many components.

Debug a little more with F7
function TDirect2DCanvas.GetRenderTarget: ID2D1RenderTarget;
begin
  if not Assigned(FRenderTarget) then  <<< this is the error on vcl.direct2d
    CreateRenderTarget;
  Result := FRenderTarget;
end;

**Comment by fpiette** [comment]
If I remember well, D10.2.3 has issues with headers. It has been fixed in D10.4 IMO. Upgrade to latest Delphi.

**Comment by limelect** [comment]
Just for this?
Thanks.
I have been using Delphi since #1 they have almost a building from me.

**Comment by fpiette** [comment]
Does the demo works for you? I think what you are showing is your own code, not mine. You should ask for help in a forum like https://en.delphipraxis.net/forum/4-vcl/ and not here.
